install:
	python3 -m pip install pip --upgrade
	python3 -m pip install -r requirements.txt --upgrade --user

run:
	python3 -m streamlit run main.py \
		--server.allowRunOnSave=true --server.runOnSave=true
