"""Agent with Planning, Reasoning & Informational Resources."""


from __future__ import annotations

from dataclasses import dataclass, field
from pprint import pprint
from typing import TYPE_CHECKING
from loguru import logger

from openssa.l2.task.status import TaskStatus
from openssa.l2.planning.hierarchical.planner import AutoHTPlanner
from openssa.l2.planning.hierarchical.planner import PlanFailure
from openssa.l2.reasoning.ooda import OodaReasoner
from openssa.l2.task.task import Task

if TYPE_CHECKING:
    from openssa.l2.planning.abstract.plan import APlan, AskAnsPair
    from openssa.l2.planning.abstract.planner import APlanner
    from openssa.l2.reasoning.abstract import AReasoner
    from openssa.l2.resource.abstract import AResource
    from openssa.l2.planning.hierarchical.plan import HTP

@dataclass
class Agent:
    """Agent with Planning, Reasoning & Informational Resources."""

    # Planner for decomposing tasks into executable solution Plans
    # using Automated Hierarchical Task Planner by default
    planner: APlanner | None = field(default_factory=AutoHTPlanner)

    # Reasoner for working through individual Tasks to either conclude or make partial progress on them
    # using OODA by default
    reasoner: AReasoner = field(default_factory=OodaReasoner)

    # set of Informational Resources for answering information-querying questions
    resources: set[AResource] = field(default_factory=set)

    @property
    def resource_overviews(self) -> dict[str, str]:
        """Overview available Informational Resources."""
        return {r.unique_name: r.overview for r in self.resources}

    def solve(self, problem: str, plan: APlan | None = None, dynamic: bool = True) -> str:
        """Solve posed Problem.

        Solution Plan can optionally be explicitly provided,
        or would be automatically generated by default if Planner is given.

        Solution Plan, whether explicitly provided or automatically generated,
        can be executed Dynamically (i.e., with as-needed further task decomposition)
        or Statically (i.e., literally per the Plan).
        """
        match (plan, self.planner, dynamic):

            # NO PLAN
            case (None, None, _):
                # if neither Plan nor Planner is given, directly use Reasoner
                logger.debug('No Plan or Planner given; directly using Reasoner')
                result: str = self.reasoner.reason(task=Task(ask=problem, resources=self.resources))

            # AUTOMATED STATIC PLAN
            case (None, _, False) if self.planner:
                # if no Plan is given but Planner is, and if solving statically,
                # then use Planner to generate static Plan,
                # then execute such static Plan
                logger.debug('No Plan given; using Planner to generate static Plan')
                plan: HTP = self.planner.plan(problem=problem, resources=self.resources)
                pprint(plan)
                result: str = plan.execute(reasoner=self.reasoner)

            # AUTOMATED DYNAMIC PLAN
            case (None, _, True) if self.planner:
                # if no Plan is given but Planner is, and if solving dynamically,
                # then first directly use Reasoner,
                # and if that does not work, then use Planner to decompose 1 level more deeply,
                # and recurse until reaching confident solution or running out of depth
                logger.debug('No Plan given; using Planner to generate dynamic Plan')
                result: str = self.solve_dynamically(problem=problem)

            # EXPERT-SPECIFIED STATIC PLAN
            case (_, None, _) if plan:
                # if Plan is given but no Planner is, then execute Plan statically
                logger.debug('Plan given but no Planner; executing Plan statically')
                result: str = plan.execute(reasoner=self.reasoner)

            # EXPERT-SPECIFIED STATIC PLAN, with Resource updating
            case (_, _, False) if (plan and self.planner):
                # if both Plan and Planner are given, and if solving statically,
                # then use Planner to update Plan's resources,
                # then execute such updated static Plan
                logger.debug('Plan and Planner given; updating Plan resources and executing Plan statically')
                plan: APlan = self.planner.update_plan_resources(plan, problem=problem, resources=self.resources)
                pprint(plan)
                result: str = plan.execute(reasoner=self.reasoner)

            # EXPERT-GUIDED DYNAMIC PLAN
            case (_, _, True) if (plan and self.planner):
                # if both Plan and Planner are given, and if solving dynamically,
                logger.debug('Plan and Planner are given, execute expert Plan dynamically')
                result: str = self.solve_dynamically(problem, self.planner, plan)

            case _:
                raise ValueError('*** Invalid Plan-Planner-Dynamism Combination ***')

        return result

    def solve_dynamically(self, problem: str, planner: APlanner = None, plan: HTP = None, other_results: list[AskAnsPair] | None = None) -> str:
        """Solve posed Problem dynamically.

        When first-pass result from Reasoner is unsatisfactory, decompose Problem and recursively solve decomposed Plan.
        """
        planner = planner or self.planner

        # Base case: see if the problem is simple enough to be solved directly.
        task = Task(ask=problem, resources=self.resources, dynamic_decomposer=planner)
        self.reasoner.reason(task)
        logger.debug(f'Task: {task.ask}\nstatus: {task.status}')

        # Base case 2: the task needs decomposition but max depth has been reached.
        if task.status == TaskStatus.NEEDING_DECOMPOSITION and not planner.max_depth:
            logger.debug(f'Max depth for decomposition reached for problem: {problem}')
            task.status = TaskStatus.FAILED
            return task.result

        # Otherwise, try to solve the problem by decomposing it.
        if task.status == TaskStatus.NEEDING_DECOMPOSITION:

            # The planner is allowed certain number of attempts to plan this task.
            # When a sub-plan fails, we try to re-plan that plan's task.
            # This means that the lowest level of the hierarchy is re-planned first, then the next level up, and so on.
            attempts = 2
            failure = None
            while attempts > 0:
                attempts -= 1
                # Create a single-level plan or take the expert-provided one.
                if not plan:
                    plan: HTP = planner.one_level_deep().plan(problem, self.resources, failure)

                # Try solving the sub-plans.
                sub_results = []
                for sub_plan in plan.sub_plans:
                    sub_task: Task = sub_plan.task
                    sub_planner: AutoHTPlanner = planner.one_fewer_level_deep()
                    sub_task.result: str = self.solve_dynamically(sub_task.ask, sub_planner, sub_results)
                    sub_results.append((sub_task.ask, sub_task.result))
                    if sub_task.status == TaskStatus.FAILED:
                        # parent task fails?
                        failure = PlanFailure(failed_plan=plan, failed_task=sub_task.ask, failed_result=sub_task.result)
                        break

                # If all of the sub-tasks are done, then we can proceed.
                if all(sub_plan.task.status == TaskStatus.DONE for sub_plan in plan.sub_plans):
                    logger.debug('All sub-tasks done.')
                    task.result: str = plan.execute(self.reasoner, other_results)
                    task.status: TaskStatus = TaskStatus.DONE
                    break

                # Otherwise, try again.
                logger.debug('Re-planning, subtask failed.')

            # If we reach this point, we have failed to solve the problem after decomposition and re-planning.

        # Once all the sub-tasks are done or the task itself is done, synthesize the results.
        return task.result
