install:
	python3 -m pip install pip --upgrade
	python3 -m pip install -r requirements.txt

run:
	OPENAI_API_KEY=AITOMATIC streamlit run main.py \
		--server.allowRunOnSave=true --server.runOnSave=true
