agent-solve:
	@poetry run python htp_oodar_agent.py ${prob}

semikong-answer:
	@poetry run python semikong_lm.py ${question}

streamlit-run:
	@poetry run streamlit run streamlit-main.py --server.allowRunOnSave=true --server.runOnSave=true
